services:

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    env_file:
      - .env  # .env 파일을 Docker 컨테이너에 로드
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/user_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - "8082:8080"

  cart-service:
    container_name: cart-service
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    env_file:
      - .env  # .env 파일을 Docker 컨테이너에 로드
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://cart-db:3306/cart_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - cart-db
    ports:
      - "8083:8080"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    env_file:
      - .env  # .env 파일을 Docker 컨테이너에 로드
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://order-db:3306/order_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - "8084:8080"

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    env_file:
      - .env  # .env 파일을 Docker 컨테이너에 로드
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://product-db:3306/product_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - "8085:8080"

  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # MySQL root 비밀번호
      MYSQL_DATABASE: user_service
    ports:
      - "3309:3306" # user-service용 MySQL 포트
    volumes:
      - user-db-data:/var/lib/mysql

  cart-db:
    image: mysql:8.0
    container_name: cart-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cart_service
    ports:
      - "3310:3306" # cart-service용 MySQL 포트
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 3
    volumes:
      - cart-db-data:/var/lib/mysql

  order-db:
    image: mysql:8.0
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # MySQL root 비밀번호
      MYSQL_DATABASE: order_service
    ports:
      - "3311:3306" # order-service용 MySQL 포트
    volumes:
      - order-db-data:/var/lib/mysql

  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # MySQL root 비밀번호
      MYSQL_DATABASE: product_service
    ports:
      - "3312:3306" # product-service용 MySQL 포트
    volumes:
      - product-db-data:/var/lib/mysql


  redis:
    image: redis:7.0
    container_name: redis-container
    restart: always
    ports:
      - "${REDIS_PORT}:6379" # 로컬 6379 포트를 컨테이너의 6379 포트로 매핑
    command: ["redis-server", "--appendonly", "yes"] # 영속성을 위한 AOF 설정
    volumes:
      - redis-data:/data # Redis 데이터 영속성

volumes:
  mysql-data:
  user-db-data:
  cart-db-data:
  order-db-data:
  product-db-data:
  redis-data:
