server:
  port: 9000
  address: 0.0.0.0
  tomcat:
    max-threads: 300
    accept-count: 1000

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      cache:
        enabled: true
        ttl: 300 # 캐시 유효 기간 (초 단위)
    gateway:
      httpclient:
        connect-timeout: 10000 # 10초
        response-timeout: 30000 # 30초
        pool:
          max-connections: 1000 # 동시 커넥션 수 제한
          acquire-timeout: 5000 # 연결을 기다리는 최대 시간
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - JwtFilter

        - id: product-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/products, /api/products/**

        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders, /api/orders/**
          filters:
            - JwtFilter

        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/cart/**
          filters:
            - JwtFilter

        - id: pay-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/pay/**
          filters:
            - JwtFilter
jwt:
  secret:
    key: ${JWT_SECRET_KEY:7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==}


eureka:
  client:
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: INFO
    org.springframework.security: INFO