spring:
  data:
    redis:
      host: localhost
      port: 6379       # Redis 서버의 포트 번호
      password: ""     # Redis 서버의 비밀번호 (없다면 빈 문자열)
      database: 0      # 사용할 Redis 데이터베이스 인덱스
  jpa:
    enabled: false