spring:
  docker:
    compose:
      file: docker-compose.yml
  datasource:
    url: jdbc:mysql://localhost:3308/madeby
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      address: redis://127.0.0.1:6379
      password: ""
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  mail:
    host: smtp.naver.com
    port: 465
    username: my-email@test.com
    password: mypassword
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

security:
  jwt-secret-key: ${JWT_SECRET_KEY}
  admin-token: ${ADMIN_TOKEN}