server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://user-db:3306/user_service
    username: root
    password: 1234 # MySQL root 비밀번호
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: user_service
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      enabled: true

  mail:
    host: smtp.naver.com
    port: 465
    username: windeer_@naver.com
    password: rkgus123
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}