server:
  port: 8084

spring:
  data:
    redis:
      host: localhost
      port: 6379       # Redis 서버의 포트 번호
      password: ""     # Redis 서버의 비밀번호 (없다면 빈 문자열)
      database: 0      # 사용할 Redis 데이터베이스 인덱스
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3309/order_service
    username: root
    password: 1234 # MySQL root 비밀번호
  jpa:
    hibernate:
      ddl-auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8에 적합한 Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG