server:
  port: 8085
  tomcat:
    max-threads: 500          # 최대 스레드 수
    accept-count: 5000         # 대기 큐의 최대 연결 수
    connection-timeout: 20000 # 연결 타임아웃(ms)
    max-connections: 10000

spring:
  cloud:
    loadbalancer:
      cache:
        enabled: true
        ttl: 300 # 캐시 유효 기간 (초 단위)
  application:
    name: product-service

  datasource:
    hikari:
      maximum-pool-size: 120  # 최대 연결 수
    url: jdbc:mysql://localhost:3309/product_service
    username: root
    password: 1234 # MySQL root 비밀번호
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.web: INFO