server:
  port: 8083

spring:
  cloud:
    loadbalancer:
      cache:
        enabled: true
        ttl: 300 # 캐시 유효 기간 (초 단위)
  data:
    redis:
      host: localhost
      port: 6379       # Redis 서버의 포트 번호
      password: ""     # Redis 서버의 비밀번호 (없다면 빈 문자열)
      database: 0      # 사용할 Redis 데이터베이스 인덱스

  datasource:
    url: jdbc:mysql://localhost:3309/cart_service
    username: root
    password: 1234 # MySQL root 비밀번호
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: cart-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG